import { useEffect, useMemo, useRef, useState } from 'react';
import { apiFetch } from './api';

const initialExpenses = [
  { id: 1, merchant: 'Swiggy', category: 'Food', amount: 420, date: '2026-09-18', note: 'Dinner' },
  { id: 2, merchant: 'Uber', category: 'Travel', amount: 280, date: '2026-09-17', note: 'Office commute' },
  { id: 3, merchant: 'Netflix', category: 'Subscriptions', amount: 649, date: '2026-09-15', note: 'Monthly plan' },
  { id: 4, merchant: 'Amazon', category: 'Shopping', amount: 1890, date: '2026-09-12', note: 'Home supplies' },
  { id: 5, merchant: 'BigBasket', category: 'Groceries', amount: 2310, date: '2026-09-10', note: 'Weekly groceries' },
];

const assets = [
  { symbol: 'ETH', name: 'Ethereum', amount: 1.82, price: 291450, change: 4.8 },
  { symbol: 'USDC', name: 'USD Coin', amount: 820, price: 83.5, change: 0.1 },
  { symbol: 'USDT', name: 'Tether', amount: 510, price: 83.6, change: -0.2 },
];
const txs = [
  { hash: '0x7a9e...c421', type: 'Received', asset: 'ETH', amount: 0.34, value: 99093, from: '0x19b4...A91C', to: '0x8c21...77E2', network: 'Ethereum', status: 'Confirmed', gas: 812 },
  { hash: '0x2bf1...a88e', type: 'Sent', asset: 'USDC', amount: 240, value: 20040, from: '0x8c21...77E2', to: '0x41af...19D0', network: 'Ethereum', status: 'Confirmed', gas: 421 },
  { hash: '0x9d32...bb10', type: 'Received', asset: 'USDT', amount: 500, value: 41800, from: '0x6a31...91D2', to: '0x8c21...77E2', network: 'Ethereum', status: 'Confirmed', gas: 398 },
  { hash: '0x5d71...91c2', type: 'Sent', asset: 'ETH', amount: 0.08, value: 23316, from: '0x8c21...77E2', to: '0x9f11...0AB2', network: 'Ethereum', status: 'Pending', gas: 690 },
];

const nav = [
  ['dashboard', 'Overview', '⌂'],
  ['funds', 'Funds', '₹'],
  ['expenses', 'Expenses', '↘'],
  ['ocr', 'Receipt OCR', '▧'],
  ['ai', 'AI Assistant', '✦'],
  ['analytics', 'Analytics', '◔'],
  ['wallet', 'Wallet', '◇'],
  ['assets', 'Assets', '◈'],
  ['transactions', 'Transactions', '↕'],
  ['portfolio', 'Portfolio', '◒'],
  ['security', 'Security', '✓'],
  ['settings', 'Settings', '⚙'],
];

const money = (n, currency = 'INR') => currency === 'USD' ? `$${(n / 83.5).toLocaleString('en-US', { maximumFractionDigits: 0 })}` : `₹${Number(n).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;

function Card({ children, className = '' }) { return <div className={`card ${className}`}>{children}</div>; }
function Pill({ children, tone = 'neutral' }) { return <span className={`pill ${tone}`}>{children}</span>; }
function BarChart({ data }) { const max = Math.max(...data.map(x => x.value), 1); return <div className="bars">{data.map(x => <div className="bar-wrap" key={x.label}><div className="bar" style={{ height: `${Math.max(8, x.value / max * 150)}px` }} /><span>{x.label}</span></div>)}</div>; }
function Donut({ items }) { const total = items.reduce((a,b)=>a+b.value,0)||1; let cursor=0; const stops=items.map(i=>{const start=cursor/total*360; cursor+=i.value; return `${i.color} ${start}deg ${cursor/total*360}deg`;}).join(','); return <div className="donut" style={{background:`conic-gradient(${stops})`}}><div className="donut-hole"><strong>{money(total)}</strong><small>monthly</small></div></div>; }

function App() {
  const [page, setPage] = useState('dashboard');
  const [dark, setDark] = useState(localStorage.getItem('arth-theme') === 'dark');
  const [language, setLanguage] = useState(localStorage.getItem('arth-lang') || 'English');
  const [currency, setCurrency] = useState(localStorage.getItem('arth-currency') || 'INR');
  const [expenses, setExpenses] = useState(initialExpenses);
  const [modal, setModal] = useState(null);
  const [search, setSearch] = useState('');
  const [chat, setChat] = useState([{role:'assistant', text:'Namaste. I can help you understand spending, cash flow, or your digital assets. What would you like to explore?'}]);
  const [question, setQuestion] = useState('');
  const [listening, setListening] = useState(false);
  const [transcript, setTranscript] = useState('');
  const recognition = useRef(null);
  const [ocrText, setOcrText] = useState('');
  const [ocrResult, setOcrResult] = useState(null);

  useEffect(()=>{ document.documentElement.classList.toggle('dark', dark); localStorage.setItem('arth-theme', dark?'dark':'light'); },[dark]);
  useEffect(()=>{ localStorage.setItem('arth-lang', language); localStorage.setItem('arth-currency', currency); },[language,currency]);

  const filtered = expenses.filter(e => `${e.merchant} ${e.category} ${e.note}`.toLowerCase().includes(search.toLowerCase()));
  const totalExpenses = expenses.reduce((s,e)=>s+e.amount,0);
  const categoryData = useMemo(()=>Object.entries(expenses.reduce((a,e)=>(a[e.category]=(a[e.category]||0)+e.amount,a),{})).map(([label,value],i)=>({label,value,color:['#6C63FF','#00A884','#F4A261','#E76F51','#F2C94C'][i%5]})),[expenses]);
  const monthBars = [{label:'Mon',value:2200},{label:'Tue',value:3400},{label:'Wed',value:1800},{label:'Thu',value:4100},{label:'Fri',value:3200},{label:'Sat',value:5200},{label:'Sun',value:2700}];

  function addExpense(e){ e.preventDefault(); const f=new FormData(e.currentTarget); setExpenses(x=>[{id:Date.now(),merchant:f.get('merchant'),category:f.get('category'),amount:Number(f.get('amount')),date:f.get('date'),note:f.get('note')},...x]); setModal(null); }
  async function askAI(text=question){ if(!text.trim()) return; const q=text.trim(); setQuestion(''); setChat(c=>[...c,{role:'user',text:q},{role:'assistant',text:'Thinking…'}]); try { const r=await apiFetch('/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})}); const d=await r.json(); setChat(c=>[...c.slice(0,-1),{role:'assistant',text:d.answer||'I can help with your spending and wallet demo data.'}]); } catch { setChat(c=>[...c.slice(0,-1),{role:'assistant',text:'I’m using demo intelligence right now. Based on your current data, your largest spending category is '+(categoryData.sort((a,b)=>b.value-a.value)[0]?.label||'not available')+'.'}]); } }
  function startVoice(){ const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){setTranscript('Voice recognition is not available in this browser. You can type instead.');return;} recognition.current=new SR(); recognition.current.lang=language==='हिंदी'?'hi-IN':'en-IN'; recognition.current.interimResults=true; recognition.current.onresult=e=>setTranscript(Array.from(e.results).map(r=>r[0].transcript).join('')); recognition.current.onend=()=>setListening(false); recognition.current.start(); setListening(true); }
  function stopVoice(){ recognition.current?.stop(); setListening(false); }
  async function runOCR(){ setOcrResult({merchant:'Cafe Coffee Day',amount:540,date:'2026-09-19',category:'Food',note:'Mock OCR result — please review before saving.'}); try{const r=await apiFetch('/ocr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:ocrText||'Cafe Coffee Day 540 19 Sep'})}); if(r.ok){const d=await r.json();setOcrResult(d)}}catch{} }

  const title = nav.find(x=>x[0]===page)?.[1] || 'Overview';
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">A</div><div><strong>ArthDrishti</strong><span>wealth, understood.</span></div></div>
      <div className="nav-group"><small>ARTH BODH</small>{nav.slice(0,6).map(([id,label,icon])=><button className={page===id?'nav-item active':'nav-item'} onClick={()=>setPage(id)} key={id}><b>{icon}</b>{label}</button>)}</div>
      <div className="nav-group"><small>ARTH RAKSHA</small>{nav.slice(6,11).map(([id,label,icon])=><button className={page===id?'nav-item active':'nav-item'} onClick={()=>setPage(id)} key={id}><b>{icon}</b>{label}</button>)}</div>
      <div className="nav-bottom"><button className={page==='settings'?'nav-item active':'nav-item'} onClick={()=>setPage('settings')}><b>⚙</b>Settings</button><div className="safe-note">● Demo mode<br/><span>Blockchain data is mock.</span></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><p className="eyebrow">{page==='wallet'||page==='assets'||page==='transactions'||page==='portfolio'||page==='security'?'ARTH RAKSHA':'ARTH BODH'}</p><h1>{language==='हिंदी'&&page==='dashboard'?'आपका वित्तीय डैशबोर्ड':title}</h1></div><div className="top-actions"><button className="icon-btn" onClick={()=>setDark(!dark)}>{dark?'☀':'◐'}</button><button className="profile">DV</button></div></header>
      <div className="content">
        {page==='dashboard'&&<Dashboard setPage={setPage} expenses={expenses} totalExpenses={totalExpenses} categoryData={categoryData} currency={currency} />}
        {page==='funds'&&<Funds currency={currency} />}
        {page==='expenses'&&<Expenses expenses={filtered} search={search} setSearch={setSearch} onAdd={()=>setModal('expense')} onDelete={id=>setExpenses(x=>x.filter(e=>e.id!==id))} currency={currency} />}
        {page==='ocr'&&<OCR ocrText={ocrText} setOcrText={setOcrText} runOCR={runOCR} result={ocrResult} save={r=>{setExpenses(x=>[{id:Date.now(),merchant:r.merchant,category:r.category,amount:r.amount,date:r.date,note:r.note},...x]);setOcrResult(null)}} />}
        {page==='ai'&&<AI chat={chat} question={question} setQuestion={setQuestion} askAI={askAI} listening={listening} startVoice={startVoice} stopVoice={stopVoice} transcript={transcript} setTranscript={setTranscript} />}
        {page==='analytics'&&<Analytics categoryData={categoryData} monthBars={monthBars} totalExpenses={totalExpenses} currency={currency} />}
        {page==='wallet'&&<Wallet />}
        {page==='assets'&&<Assets currency={currency} />}
        {page==='transactions'&&<Transactions search={search} setSearch={setSearch} />}
        {page==='portfolio'&&<Portfolio currency={currency} categoryData={categoryData} />}
        {page==='security'&&<Security />}
        {page==='settings'&&<Settings dark={dark} setDark={setDark} language={language} setLanguage={setLanguage} currency={currency} setCurrency={setCurrency} />}
      </div>
    </main>
    {modal==='expense'&&<div className="modal-backdrop"><form className="modal" onSubmit={addExpense}><div className="modal-head"><h2>Add expense</h2><button type="button" onClick={()=>setModal(null)}>×</button></div><input name="merchant" required placeholder="Merchant"/><input name="amount" required type="number" placeholder="Amount (INR)"/><select name="category" defaultValue="Food"><option>Food</option><option>Travel</option><option>Shopping</option><option>Groceries</option><option>Subscriptions</option><option>Health</option><option>Other</option></select><input name="date" type="date" defaultValue="2026-09-19"/><input name="note" placeholder="Note"/><button className="primary">Save expense</button></form></div>}
  </div>;
}

function Dashboard({setPage,expenses,totalExpenses,categoryData,currency}){return <><div className="hero"><div><Pill tone="purple">Financial command center</Pill><h2>Understand today.<br/><span>Protect tomorrow.</span></h2><p>Arth Bodh makes everyday money visible; Arth Raksha keeps digital assets in view.</p><div className="hero-actions"><button className="primary" onClick={()=>setPage('expenses')}>Add expense</button><button className="secondary" onClick={()=>setPage('ai')}>Ask Arth AI ✦</button></div></div><div className="hero-orb"><div className="orb-inner">₹84.2K<br/><small>available funds</small></div></div></div><div className="metric-grid"><Card><span>Available funds</span><strong>{money(84200,currency)}</strong><small className="positive">+8.4% this month</small></Card><Card><span>Monthly spending</span><strong>{money(totalExpenses,currency)}</strong><small>of ₹38,000 budget</small></Card><Card><span>Crypto portfolio</span><strong>{money(682940,currency)}</strong><small className="positive">+4.2% today</small></Card><Card><span>Security status</span><strong>Protected</strong><small className="positive">3 checks passed</small></Card></div><div className="two-col"><Card><div className="card-title"><div><span>Recent expenses</span><h3>Money in motion</h3></div><button className="link" onClick={()=>setPage('expenses')}>View all →</button></div>{expenses.slice(0,4).map(e=><div className="row" key={e.id}><div className="avatar">{e.merchant[0]}</div><div className="row-main"><strong>{e.merchant}</strong><span>{e.category} · {e.date}</span></div><b>-{money(e.amount,currency)}</b></div>)}</Card><Card><div className="card-title"><div><span>Spending mix</span><h3>Where it goes</h3></div><button className="link" onClick={()=>setPage('analytics')}>Analytics →</button></div><div className="donut-row"><Donut items={categoryData}/><div>{categoryData.slice(0,4).map(x=><div className="legend" key={x.label}><i style={{background:x.color}}></i><span>{x.label}</span><b>{money(x.value,currency)}</b></div>)}</div></div></Card></div></>}
function Funds({currency}){return <><div className="section-intro"><Pill tone="green">Live overview</Pill><h2>Your money, clearly accounted for.</h2><p>Balances are demo values until a bank connection is configured.</p></div><div className="metric-grid three"><Card><span>Total funds</span><strong>{money(124800,currency)}</strong><small>Across 3 accounts</small></Card><Card><span>Income this month</span><strong>{money(97000,currency)}</strong><small className="positive">+12.8% vs last month</small></Card><Card><span>Remaining budget</span><strong>{money(38200,currency)}</strong><small>₹38,000 planned spend</small></Card></div><Card><div className="card-title"><div><span>Accounts</span><h3>Balances</h3></div><Pill>Demo data</Pill></div>{[['HDFC Savings','•• 4421',64000],['ICICI Salary','•• 1098',42800],['Cash wallet','Physical cash',18000]].map(a=><div className="account" key={a[0]}><div><strong>{a[0]}</strong><span>{a[1]}</span></div><b>{money(a[2],currency)}</b></div>)}</Card></>}
function Expenses({expenses,search,setSearch,onAdd,onDelete,currency}){return <><div className="section-intro"><Pill tone="purple">Arth Bodh</Pill><h2>Expenses, without the spreadsheet.</h2><p>Capture, review and understand every outgoing rupee.</p></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search merchant, category or note…"/><button className="primary" onClick={onAdd}>+ Add expense</button></div><Card><div className="table"><div className="thead"><span>Merchant</span><span>Category</span><span>Date</span><span>Amount</span><span></span></div>{expenses.map(e=><div className="trow" key={e.id}><div><strong>{e.merchant}</strong><small>{e.note}</small></div><Pill>{e.category}</Pill><span>{e.date}</span><b>-{money(e.amount,currency)}</b><button className="delete" onClick={()=>onDelete(e.id)}>Delete</button></div>)}</div>{!expenses.length&&<Empty text="No expenses match your search."/>}</Card></>}
function OCR({ocrText,setOcrText,runOCR,result,save}){return <><div className="section-intro"><Pill tone="orange">Mock OCR</Pill><h2>Turn a receipt into a clean expense.</h2><p>Upload integration is represented by a safe demo flow. The extracted fields are always editable before saving.</p></div><Card><div className="dropzone"><div className="upload-icon">▧</div><h3>Drop receipt here</h3><p>or paste receipt text below</p><textarea value={ocrText} onChange={e=>setOcrText(e.target.value)} placeholder="Example: Cafe Coffee Day ₹540 19 Sep"/><button className="primary" onClick={runOCR}>Extract receipt</button></div></Card>{result&&<Card className="review"><div className="card-title"><div><span>Review before saving</span><h3>Extracted fields</h3></div><Pill tone="orange">Mock OCR</Pill></div><div className="form-grid"><label>Merchant<input value={result.merchant} onChange={e=>result.merchant=e.target.value}/></label><label>Amount<input type="number" value={result.amount} onChange={e=>result.amount=Number(e.target.value)}/></label><label>Category<input value={result.category} onChange={e=>result.category=e.target.value}/></label><label>Date<input value={result.date} onChange={e=>result.date=e.target.value}/></label></div><button className="primary" onClick={()=>save(result)}>Save as expense</button></Card>}</>}
function AI({chat,question,setQuestion,askAI,listening,startVoice,stopVoice,transcript,setTranscript}){return <><div className="section-intro"><Pill tone="purple">Arth AI</Pill><h2>A calmer way to ask about money.</h2><p>Ask about your spending patterns, explain a transaction, or turn a voice note into an expense.</p></div><Card className="chat-card"><div className="suggestions">{['Why did I spend more this month?','What is my largest category?','Summarize my cash flow'].map(x=><button key={x} onClick={()=>askAI(x)}>{x}</button>)}</div><div className="chat-window">{chat.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.text}</div>)}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();askAI()}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask Arth AI…"/><button type="button" className={listening?'voice active':'voice'} onClick={listening?stopVoice:startVoice}>{listening?'■':'●'}</button><button className="primary">Send</button></form><div className="voice-review"><label>Voice transcription</label><textarea value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Your transcription appears here for review…"/><button className="secondary" onClick={()=>askAI(transcript)}>Send transcription</button></div></Card></>}
function Analytics({categoryData,monthBars,totalExpenses,currency}){return <><div className="section-intro"><Pill tone="green">Analytics</Pill><h2>See the patterns, not just the numbers.</h2><p>Demo analytics based on your current local expense data.</p></div><div className="two-col"><Card><div className="card-title"><div><span>Weekly spend</span><h3>{money(totalExpenses,currency)}</h3></div><Pill>7 days</Pill></div><BarChart data={monthBars}/></Card><Card><div className="card-title"><div><span>Categories</span><h3>Spending mix</h3></div></div><div className="donut-row"><Donut items={categoryData}/><div>{categoryData.map(x=><div className="legend" key={x.label}><i style={{background:x.color}}></i><span>{x.label}</span><b>{money(x.value,currency)}</b></div>)}</div></div></Card></div></>}
function Wallet(){return <><div className="wallet-hero"><div><Pill tone="green">Connected · Demo</Pill><h2>0x8c21…77E2</h2><p>Ethereum Mainnet · Watch-only wallet</p></div><button className="secondary">Copy address</button></div><div className="metric-grid three"><Card><span>Total portfolio</span><strong>₹6,82,940</strong><small className="positive">+4.2% today</small></Card><Card><span>Network</span><strong>Ethereum</strong><small>Gas tracked separately</small></Card><Card><span>Security</span><strong>Protected</strong><small className="positive">No risky approvals found</small></Card></div><Card><div className="card-title"><div><span>Safety boundary</span><h3>What Arth Raksha never asks for</h3></div></div><div className="safe-grid"><div>✓ Seed phrases</div><div>✓ Private keys</div><div>✓ Recovery phrases</div><div>✓ Signing secrets</div></div></Card></>}
function Assets({currency}){return <><div className="section-intro"><Pill tone="green">Demo blockchain data</Pill><h2>Your digital assets at a glance.</h2><p>Balances and prices are mock values for product demonstration.</p></div><Card><div className="table"><div className="thead"><span>Asset</span><span>Balance</span><span>Price</span><span>Value</span><span>24h</span></div>{assets.map(a=><div className="trow" key={a.symbol}><div><strong>{a.symbol}</strong><small>{a.name}</small></div><span>{a.amount}</span><span>{money(a.price,currency)}</span><b>{money(a.amount*a.price,currency)}</b><span className={a.change>=0?'positive':'negative'}>{a.change>0?'+':''}{a.change}%</span></div>)}</div></Card></>}
function Transactions({search,setSearch}){const rows=txs.filter(t=>Object.values(t).join(' ').toLowerCase().includes(search.toLowerCase()));return <><div className="section-intro"><Pill tone="green">Activity</Pill><h2>Transactions with context.</h2><p>Every row includes the network, status, gas and counterparties.</p></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search hash, asset, address…"/></div><Card><div className="table"><div className="thead"><span>Transaction</span><span>Asset</span><span>Value</span><span>Status</span><span>Network</span></div>{rows.map(t=><div className="trow" key={t.hash}><div><strong>{t.type} · {t.hash}</strong><small>{t.from} → {t.to}</small></div><span>{t.asset} {t.amount}</span><b>{money(t.value)}</b><Pill tone={t.status==='Confirmed'?'green':'orange'}>{t.status}</Pill><span>{t.network} · gas ₹{t.gas}</span></div>)}</div></Card></>}
function Portfolio({currency}){return <><div className="section-intro"><Pill tone="green">Portfolio</Pill><h2>Allocation you can actually read.</h2><p>Mock balances shown in INR; USD is available in Settings.</p></div><div className="portfolio-grid"><Card className="portfolio-total"><span>Total value</span><strong>{money(682940,currency)}</strong><small className="positive">+₹27,840 today</small><div className="allocation"><div style={{width:'78%'}}></div><div style={{width:'12%'}}></div><div style={{width:'10%'}}></div></div><div className="legend"><i></i><span>ETH</span><b>78%</b></div><div className="legend"><i></i><span>USDC</span><b>12%</b></div><div className="legend"><i></i><span>USDT</span><b>10%</b></div></Card><Card><div className="card-title"><div><span>Performance</span><h3>30 day view</h3></div></div><BarChart data={[{label:'1',value:62},{label:'5',value:70},{label:'10',value:68},{label:'15',value:81},{label:'20',value:78},{label:'25',value:91},{label:'30',value:96}]}/></Card></div></>}
function Security(){return <><div className="section-intro"><Pill tone="green">Security center</Pill><h2>Protect the wallet without touching secrets.</h2><p>Arth Raksha monitors public wallet signals and explains risks before you act.</p></div><div className="metric-grid three"><Card><span>Wallet risk</span><strong className="positive">Low</strong><small>Public signals only</small></Card><Card><span>Approvals</span><strong>3</strong><small className="positive">No high-risk approval</small></Card><Card><span>Address checks</span><strong>8 / 8</strong><small className="positive">Verified in demo</small></Card></div><Card><div className="security-list">{[['✓','Network matches','Ethereum Mainnet'],['✓','Recipient format','Valid EVM address'],['✓','Known scam database','No match in demo set'],['!','Transaction confirmation','Review amount and recipient before signing']].map(x=><div className="security-row" key={x[1]}><span className={x[0]==='!'?'warn':'check'}>{x[0]}</span><div><strong>{x[1]}</strong><small>{x[2]}</small></div><button className="link">Review →</button></div>)}</div></Card></>}
function Settings({dark,setDark,language,setLanguage,currency,setCurrency}){return <><div className="section-intro"><Pill>Preferences</Pill><h2>Make ArthDrishti yours.</h2><p>Your choices are saved locally in this browser.</p></div><Card><div className="settings-row"><div><strong>Theme</strong><small>Light or dark interface</small></div><div className="seg"><button className={!dark?'selected':''} onClick={()=>setDark(false)}>Light</button><button className={dark?'selected':''} onClick={()=>setDark(true)}>Dark</button></div></div><div className="settings-row"><div><strong>Language</strong><small>English / हिंदी</small></div><div className="seg"><button className={language==='English'?'selected':''} onClick={()=>setLanguage('English')}>English</button><button className={language==='हिंदी'?'selected':''} onClick={()=>setLanguage('हिंदी')}>हिंदी</button></div></div><div className="settings-row"><div><strong>Currency</strong><small>Display preference</small></div><div className="seg"><button className={currency==='INR'?'selected':''} onClick={()=>setCurrency('INR')}>INR ₹</button><button className={currency==='USD'?'selected':''} onClick={()=>setCurrency('USD')}>USD $</button></div></div></Card></>}
function Empty({text}){return <div className="empty">{text}</div>}
export default App;
